language: node_js
node_js:
- 11.2.0
branches:
  only:
  - master
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: dYhXxw44XDKNkOhq3GiIJjwIe2/CtMblRDxPtIrFPZq1cCQ1dhftsd2OXjL78f4sQYwVqHVmjoDIkFDxib+o5RDtp8meck+ikLenyTTPqV9vwrWvX5wq1pYmqfYau21kMIVfZSjjyUJiibFGQTzyILgkTqvs4mnxWDBEqQX6avcpaNKmu0qhW1PDa/MXuLjMe8S/M7yrz9x7r3GkWfditxzegvHhCNvLAI2Wixm7B7m3oNXJZtea1Eff0nlO+a/2dnPWUT2Coe6jt8jjLGzrR6mJjDnjgvviL06Lfhwqqo3XTZuHwTfiMkOnFSDrhWgHa8Ang6SOi/MuF8XQVO2zXTo0znqrQYDgjW7rAAy9OfwwCQA4ByKP4Q4iW5m9aRSKYogKkAk5PvYpIARWMZMvPOA1cdXQ5B2MRA69uXJsZUfC1A0QdcdKm9HgmhEyJ9YomU6MxU72CU2mDTYLB/eWt/Ox/G63JyTEPrgAa71pp/rxZB46mKPvydgzoksaIUFfu9zkizfmQa7zbtKbI7LNqXPWcbsD+eKIwUSv5p6DncU14vW60i6NJbKBTnLNUDSQPrYJckxxDTlBPGYXm143ipEHbke9s/WTCuH65kGUfLsfI9QTuyVxgXATvB0/sEAIalV9TqluQ88Z6rs5lqWkb+If1DKgvMFobR8W9h9eKLg=
  message: "Deploying Emerson Vicuna DDS website"