language: node_js
node_js:
- 11.2.0
branches:
  only:
  - master
cache:
  directories:
  - node_modules
script:
- npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  token:
    secure: hWpv6/rlPdzjBHwTPbSW+Hodxy8AVFnZ09CK7EuSHH8Wv0HS2ivMRLWQ3/WbSCZDMMprCcGv/xXDiVHwJkWO3skFO10qzeOmUiR1xIbSmXlZi1CEObSjp+f1NE9XaxrhAE9KP8cX48YuQ2WYKwyNlNOVxJFReOTTWhIzJ9ubItKj7AyJtqLgmCaLEQdroHQoKgxpKlYfirgeyJ3F4XKXnFN4XMr166O4w7G+Eaffuk1XxbpqNRUwRW5R67KB21ZY3cBxa7CRhNUtV13Lr85u69Dv3YHUern+u1ezojmr+zwLJ1BEbm9lp7CZWS9RQ4HKj5S+l1cuufTssONI6I4XQSqbzAqUdSnZuD3hOj7agsKET/A/Owa9N3M+LK5UeMSpe2eVLbvJpQU6KCznZWIhyt3WAlljffnenA5ignDdO+iStQn1z4u8yWNGfFI74P4P+4qC7KeborI9zkN1NSI/06jRedk8oHaM5jklZdGZW6aYru+7fbk/9IS0m6rE/K26wmKPS8UVOULxMkDMCzwEMjTFjvIjTMEQY6BdqfKfMKuy5dVKqlOyCvJ1coIAV+GuvplovJ/Umt8T0n/UYfyhgTCnR1aIrCD7ksSnllsGFToLoGHTIuk5iuiIm4/tGFw+hHnlLMdD+4VGsaW2jrXRIFIAexF5o4AEGYqlOxJgktw=
  message: "Deploying Emerson Vicuna DDS website"
