language: node_js
node_js:
  - "11.2.0"

branches:
  only:
    - master

cache:
  directories:
  - node_modules

script:
  - npm run build

deploy:
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_TOKEN




#jobs:
#  include:
#    - stage: install
#      script: echo "Installing Dependencies" && npm i && npm i -g firebase-tools
#    - stage: build
#      script: echo "Building Application" && npm run build
#
#after_success:
#  - firebase deploy --token $FIREBASE_TOKEN && echo "Application Deployed!"