language: node_js
node_js:
  - "11.2.0"

branches:
  only:
    - master

cache:
  directories:
  - node_modules

script:
  - npm run build

deploy:
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_TOKEN